title: News collector development
description: A collection of posts
feeds:
  - site: https://blog.rust-lang.org/
    url: https://blog.rust-lang.org/feed.xml
    title: Rust-Lang Main Blog
  - site: https://stackoverflow.com/questions/tagged/rust
    url: https://stackoverflow.com/feeds/tag/rust
    title: Rust questions on StackOverflow
  - site: https://www.reddit.com/r/rust
    url: https://www.reddit.com/r/rust.rss
    title: r/rust
  - site: https://rust.code-maven.com/
    url: https://rust.code-maven.com/atom
    title: Rust Maven
  - site: https://rust-analyzer.github.io/
    url: https://rust-analyzer.github.io/feed.xml
    title: rust-analyzer

